implemented features of deleting and opening a selected tab
legendword/tab-drawer pull request #1
Opened 2023-05-01 19:34 UTC by Zijing-Liu

2023-05-05 05:08 UTC, legendword requested changes
See my comments on the code for refactoring advices.

2023-05-05 05:08 UTC, legendword commented on src/App.vue
> +
```suggestion

```

2023-05-05 05:08 UTC, legendword commented on src/App.vue
> +            <!-- dynamic class -->
```suggestion

```

2023-05-05 05:08 UTC, legendword commented on src/App.vue
> +    DeleteSelected(windowIndex) {
Please refactor the method name to use camel case

2023-05-05 05:08 UTC, legendword commented on src/App.vue
> +
```suggestion

```

2023-05-05 05:08 UTC, legendword commented on src/App.vue
> +    },
```suggestion

```

2023-05-05 15:35 UTC, Zijing-Liu commented on src/App.vue
> +    DeleteSelected(windowIndex) {
resolved

2023-10-24 23:39 UTC, legendword approved these changes
Feature is now working as expected. Merging this now.

2023-10-24 23:41 UTC, merged